language: ruby
cache: bundler
rvm:
 - 2.2

before_install:
 - sudo service mysql restart
install:
 - bundle install --path vendor/bundle
before_script:
 - bundle exec rake db:create
 - bundle exec rake db:setup
 - bundle exec rake geo:fetch
script:
 - bundle --deployment
 - bundle exec rake ci --trace
