language: ruby
cache: bundler
addons:
  apt:
    packages:
      - libqtwebkit-dev
      - libqtwebkit4
rvm:
 - 2.2
env:
 global:
  - RAILS_ENV=test
  - QMAKE=/usr/lib64/qt5/bin/qmake
  - RAILS_DB_NAME='pitc_cryptopus_test'
  - RAILS_DB_HOST='pitc-cryptopus-test.db.puzzle.ch'
  - RAILS_DB_PORT=3306
  - RAILS_DB_ADAPTER='mysql2'
  - RAILS_DB_USERNAME='pitc_cryptopus_t'
  - RAILS_DB_PASSWORD='3dOPKS.w@5<n'
before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
 - sudo service mysql restart
before_script:
 - bundle install --path vendor/bundle
 - rake db:create
 - rake db:setup
 - rake geo:fetch
script:
 - bin/rails db:environment:set RAILS_ENV=test
 - bundle exec rake ci --trace
