language: ruby
cache: bundler
addons:
  firefox: 45.0
rvm:
 - 2.2

before_install:
 - sudo service mysql restart
install:
 - bundle install --path vendor/bundle
before_script:
 - bundle exec rake db:create
 - bundle exec rake db:setup
 - bundle exec rake db:migrate
 - bundle exec rake db:seed
 - bundle exec rake geo:fetch
script:
 - bundle --deployment
 - bundle exec rake ci --trace
 - bundle exec rake test:features
