language: ruby
cache: bundler
addons:
  apt:
    packages:
      - libqtwebkit-dev
      - libqtwebkit4
rvm:
 - 2.2
env:
 global:
  - RAILS_ENV=test
  - QMAKE=/usr/lib64/qt5/bin/qmake
  - RAILS_DB_NAME='pitc_cryptopus_test'
  - RAILS_DB_HOST='pitc-cryptopus-test.db.puzzle.ch'
  - RAILS_DB_PORT=3306
  - RAILS_DB_ADAPTER='mysql2'
  - RAILS_DB_USERNAME='pitc_cryptopus_t'
  - RAILS_DB_PASSWORD='3dOPKS.w@5<n'
before_install:
 - sudo apt-get install qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
 - sudo service mysql restart
install:
 - bundle install --path vendor/bundle
 - rake db:create
 - rake db:setup
 - rake geo:fetch
script:
 - bin/rails db:environment:set RAILS_ENV=test
 - bundle exec rake ci --trace
